# Generated by Django 5.0.1 on 2024-02-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='moviedesp',
            field=models.CharField(max_length=600),
        ),
    ]
